### ISSUE TITLE
Breaking issue in adminhtml/system.xml

### ISSUE THREAD

**Issue by ArjenMiedema** [mageplaza/magento-2-login-as-customer#14]
### Preconditions (*)

1. Install the extension at v4.0.2

### Steps to reproduce (*)

1. Go to the admin
2. Go to the configuration 

### Expected result (*)

1. Admin is working as expected

### Actual result (*)

1. A breaking error is shown because of this change: https://github.com/mageplaza/magento-2-login-as-customer/compare/v4.0.1...v4.0.2#diff-89223417b0d8b4f3be81bd4caf5573ad94c01df7d6e897cb48352e7c6204af25R34

**Comment by DHT-Uri** [comment]
Hello,

I have checked the files and tested but no errors appear. 
Please help me try using our latest core module version (1.4.11): [Download](https://github.com/mageplaza/module-core)

If it still crashes, please provide more information, I will check again.

Best Regards!

**Comment by ArjenMiedema** [comment]
@DHT-Uri There is an actual XML syntax error on the line that I mentioned and I created a fix for it here as well: https://github.com/mageplaza/magento-2-login-as-customer/pull/15

Seems like this is an error, because even the IDE shows it as an error.

**Comment by peterjaap** [comment]
I have the same issue! Plz merge

**Comment by KhietNguyen83** [comment]
Hi @peterjaap,
We have solved the problem and released in a new version.
Please dowload version 4.0.3
Thanks a lot!
