### ISSUE TITLE
not activated module

### ISSUE THREAD

**Issue by TecSecret** [mageplaza/magento-2-login-as-customer#3]
when inserting the data, it is in this infinite loop

![image](https://user-images.githubusercontent.com/6561517/58391651-29756380-800d-11e9-9682-cc1853cc6002.png)

**Comment by DrakeJack** [comment]
I'm Drake from Mageplaza and I'll assist you.
For the issue, we have updated the solution to solve it.

Please refer this link and let me know about the result:
https://github.com/mageplaza/module-core/issues/26#issue-440512550

**Comment by GKnd** [comment]
Same problem for me. Infinite loop
I came here after reading https://github.com/mageplaza/module-core/issues/26#issue-440512550

**Comment by DrakeJack** [comment]
We have updated the solution in activating the module.
Please refer: `https://github.com/mageplaza/module-core/issues/26`
