### ISSUE TITLE
After upgrading to 2.2.9 it stopped allowing checkout

### ISSUE THREAD

**Issue by mauveine** [mageplaza/magento-2-login-as-customer#4]
Hello,

We have been using this module on 2.2.5 with no issues.
In July we decided to make an upgrade to 2.2.9.

Since then, if an admin logins as customer, he cannot proceed to checkout from cart receiving the "Login" popup.

I think there is an issue with fetching the proper data when setting `$this->session->loginById($log->getCustomerId());` in the file `app/code/Mageplaza/LoginAsCustomer/Controller/Login/Index.php`.

I would like to mention that I don't have any override or plugins on the `session` or the method `loginById`

Please let me know if I need to provide any other information on this.

**Comment by LuongNgoDoan** [comment]
Hi!
We've tested on the Magento 2.2.9 but we haven't encountered the same as yours. We can still checkout as usual when logging in the customer account from the admin or frontend.
Can you please clarify more about the problem in steps by steps? It should be better if you can send us a video reproducing this.

In case we cannot replicate this issue on our local environment, and it only happens on your site, kindly submit a ticket to discuss further about it by the following link: https://www.mageplaza.com/contact.html

**Comment by mauveine** [comment]
What I mean is that if a customer has an active cart already and then we login as that customer, we cannot see it. It shows that cart is empty.

If we go in the view cart, we can see it, but it asks to login again as the respective customer again.
