### ISSUE TITLE
Compatibility with 2.3.3?

### ISSUE THREAD

**Issue by osseonews** [mageplaza/magento-2-login-as-customer#6]
Is this extension compatible with Magento 2.3.3?

**Comment by datvm231** [comment]
Hello,

Sorry for the delayed response. We have tested and made sure it compatible with Magento 2.3.3.
If you find any trouble using the extension, please feel free to ask here or contact our technical support team.
https://www.mageplaza.com/contact.html

**Comment by osseonews** [comment]
Thanks. We noticed that the extension does not use declarative schema (db_schema.xml file - see here: https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/), and Magento will soon phase out the older database scripts. Will the extension be updated to use declarative scheme per the new requirements of Magento 2.3, so it remains compatible with future versions of Magento?

**Comment by datvm231** [comment]
Thank you for the notice. It has been updated in develop branch. We will roll out to master in the future.
Here is the related commit: fa1d2e3e8817c6668a2a993da366af5ee36820f9
