### ISSUE TITLE
Not logging in Magento 2.3.5-p1 

### ISSUE THREAD

**Issue by jrosell** [mageplaza/magento-2-login-as-customer#9]
When I click "login on customer" it redirects me to login page but it doesent't log me in.

Using Magento 2.3.5-p1 on developer mode.

**Comment by Shinichi69** [comment]
Hi @jrosell 

I checked your problem on my local.
However, I can't reproduce your problem.

Please create a ticket to support your issue here:
- https://mageplaza.freshdesk.com/support/tickets/new

Thanks so much!

**Comment by Shinichi69** [comment]
Closed due no response within 7 days.
